apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: moscow-time-app
spec:
  type: LoadBalancer
  selector:
    app: moscow-time-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000