- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Ensure directory exists for /etc/apt/keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker gpg key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo_url }}"
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce={{docker_version}}
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  notify: Docker Restart

- name: Disable root access
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "userns-remap": "default"
      }
    owner: root
    group: root
    mode: "0644"
  notify: Docker Restart

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started